apiVersion: batch/v1
kind: Job
metadata:
  name: hyperpitrix-release-app-job
  namespace: openpitrix-system
  labels:
    app: hyperpitrix
    job: hyperpitrix-release-app
    version: v0.0.1
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: hyperpitrix
        job: hyperpitrix-release-app
        version: v0.0.1
      name: hyperpitrix-release-app-job
    spec:
      containers:
      - command: ["release-app","-path","/data/helm-pkg/"]
        name: hyperpitrix-release-app-job
        imagePullPolicy: IfNotPresent
        image: openpitrix/release-app
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
