name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Publish Docker Image
      uses: tinact/docker.image@1.0.1
      with:
        image_name: openpitrix/release-app
        image_tag: latest
        registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
